# Generated by Django 5.2.9 on 2025-12-18 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_curso', models.CharField(max_length=20)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('year_curso', models.IntegerField()),
                ('semestre_curso', models.IntegerField()),
                ('creditos_curso', models.IntegerField()),
                ('book_precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('examen_costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateField()),
                ('semestre', models.IntegerField()),
                ('estado', models.CharField(default='ACTIVA', max_length=20)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.RESTRICT, to='main.curso')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('parcial_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('parcial_2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('examen_final', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='main.matricula')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_std', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('correo_std', models.EmailField(blank=True, max_length=150, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('city_std', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_std',
            field=models.ForeignKey(db_column='id_std', on_delete=django.db.models.deletion.RESTRICT, to='main.student'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('correo_tutor', models.EmailField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='id_tutor',
            field=models.ForeignKey(db_column='id_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tutor'),
        ),
    ]
