# Generated by Django 5.2.9 on 2026-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tutor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(auto_now_add=True),
        ),
    ]
